const sponsorsData = [
  {
    id: 1,
    name: "Gail",
    imageUrl: "images/GAIL logo.jpg",
    type: "Title",
    link:"#",
  },  
    {
      id: 2,
      name: "The Global Hues",
      imageUrl: "images/GlobalHues.png",  
      type: "Media Partner",
      link:"https://theglobalhues.com/", 
      x: 0, y: 1000
    },
    {
      id: 3,
      name: "ED Times",
      imageUrl: "images/EDTimes.png",
      type: "Media Partner",
      link:"https://edtimes.in/",
    },
    {
      id: 4,
      name: "Youth Incorporated",
      imageUrl: "images/youthIncorporated.png",
      type: "Youth Media Partner",
      link:"https://youthincmag.com/",
    },
    {
        id: 5,
        name: "Punekar News",
        imageUrl: "images/Punekarlogo.png",
        type: "Digital Media Partner",
        link:"https://www.punekarnews.in/",
      },
      {
        id: 6,
        imageUrl: "images/campustimesSponser.png",
        name: "Campus Times Pune",
        type: "Youth Partner",
        link:"https://www.campustimespune.com/",
      },
      {
        id: 7,
        name: "MSCDA",
        imageUrl: "images/MSCDA-LOGO.png",
        type: "Associate",
        link:"#",
      },{
        id: 8,
        name: "AI OCD",
        imageUrl: "images/AIOCD logo.jpeg",
        type: "Power",
        link:"#",
      },{
        id: 9,
        name: "Quick Heal",
        imageUrl: "images/Mashaal-coloured-01.png",
        type: "Cyber Security Partner",
        link:"#",
      },{
        id: 10,
        name: "Ease My Trip",
        imageUrl: "images/Ease my trip logo.jpg",
        type: "Travel Partner",
        link:"#",
      },{
        id: 11,
        name: "Steam Lok",
        imageUrl: "images/Steam lok.jpg",
        type: "Industrial Solution  Partner",
        link:"#",
      },{
        id: 12,
        name: "Unstop",
        imageUrl: "images/unstop-logo.webp",
        type: "Powering Partner",
        link:"#",
      },{
        id: 13,
        name: "Time",
        imageUrl: "images/Mashaal-coloured-01.png",
        type: "MBA Prep Partner",
        link:"#",
      },{
        id: 14,
        name: "Max Protein",
        imageUrl: "images/Mashaal-coloured-01.png",
        type: "Protein Partner",
        link:"#",
      },{
        id: 15,
        name: "SBI",
        imageUrl: "images/SBI.jpg",
        type: "Banking Partner",
        link:"#",
      },{
        id: 16,
        name: "Gurukrupa Budhani Brothers",
        imageUrl: "images/Budhani bros.jpg",
        type: "Snacks Partner",
        link:"#",
      },{
        id: 17,
        name: "Total Sports",
        imageUrl: "images/Only Total Sports & Fitness.png",
        type: "Sporting Partner",
        link:"#",
      },{
        id: 18,
        name: "Nescafe",
        imageUrl: "images/Nescafe .jpg",
        type: "Beverage Partner",
        link:"#",
      },{
        id: 19,
        name: "AMAARY Artifrost",
        imageUrl: "images/Amaary artifrost.jpg",
        type: "Dessert Partner",
        link:"#",
      },{
        id: 20,
        name: "Jogeshwari Misal",
        imageUrl: "images/jogeshwari misal.png",
        type: "Misal Partner",
        link:"#",
      },{
        id: 21,
        name: "Zorko",
        imageUrl: "images/Zorko .jpg",
        type: "Dining Partner",
        link:"#",
      },{
        id: 22,
        name: "The wokk toss",
        imageUrl: "images/The wokk toss.jpg",
        type: "Chinese Partner",
        link:"#",
      },{
        id: 23,
        name: "Rolls Call",
        imageUrl: "images/roll call.jpg",
        type: "Wrap and Roll Partner",
        link:"#",
      },{
        id: 24,
        name: "Subs and CO",
        imageUrl: "images/Subs&Co.png",
        type: "Subway Partner",
        link:"#",
      },{
        id: 25,
        name: "LWS Defence Mania",
        imageUrl: "images/LWS defence mania.png",
        type: "Defence Exam Partner",
        link:"#",
      },{
        id: 26,
        name: "Sudama Bhel",
        imageUrl: "images/Sudama bhel.jpg",
        type: "Chaat Partner",
        link:"#",
      },{
        id: 27,
        name: "Wild Fit ",
        imageUrl: "images/Wildfit.png",
        type: "Fitness Partner",
        link:"#",
      },
      
  ];
  
  export default sponsorsData;